apiVersion: v1
kind: Service
metadata:
  name: {servicename}
  namespace: {projectnamespace}
spec:
  selector:
    app: {servicename}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 54360
  type: LoadBalancer
